### ISSUE TITLE
安装完 jupyter 后运行提示找不到 jupyter

### ISSUE THREAD

**Issue by Rhettup** [neolee/pilot#1146]
按照教材上的步骤
不管怎么安装 都是Python 3.7.3不知道为什么？
```
liweijun@liweijuns-MacBook-Pro pilot-student % python3 -V
Python 3.7.3
```
安装pip经历了很多坎坷 最后改成pip3，加上--user才通过
```
liweijun@liweijuns-MacBook-Pro pilot-student % python -m pip install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pip in /Users/liweijun/Library/Python/2.7/lib/python/site-packages (20.0.2)
liweijun@liweijuns-MacBook-Pro pilot-student % python3 -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'RECORD'
Consider using the `--user` option or check the permissions.

You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
liweijun@liweijuns-MacBook-Pro pilot-student % python3 -m pip install --upgrade pip --user
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-20.0.2
```
最后一步pip3 install jupyterlab（之前安装了），可以看到一下的反馈，应该是成功的，但是使用jupyter lab这个命令就是提示找不到jupyter
```
liweijun@liweijuns-MacBook-Pro pilot-student % pip3 install jupyterlab
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jupyterlab in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (1.2.6)
Requirement already satisfied: jinja2>=2.10 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyterlab) (2.11.1)
Requirement already satisfied: notebook>=4.3.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyterlab) (6.0.3)
Requirement already satisfied: jupyterlab-server~=1.0.0 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyterlab) (1.0.6)
Requirement already satisfied: tornado!=6.0.0,!=6.0.1,!=6.0.2 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyterlab) (6.0.3)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jinja2>=2.10->jupyterlab) (1.1.1)
Requirement already satisfied: prometheus-client in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (0.7.1)
Requirement already satisfied: ipykernel in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (5.1.4)
Requirement already satisfied: nbconvert in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (5.6.1)
Requirement already satisfied: ipython-genutils in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (0.2.0)
Requirement already satisfied: jupyter-core>=4.6.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (4.6.3)
Requirement already satisfied: jupyter-client>=5.3.4 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (5.3.4)
Requirement already satisfied: terminado>=0.8.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (0.8.3)
Requirement already satisfied: pyzmq>=17 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (18.1.1)
Requirement already satisfied: Send2Trash in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (1.5.0)
Requirement already satisfied: traitlets>=4.2.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (4.3.3)
Requirement already satisfied: nbformat in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from notebook>=4.3.1->jupyterlab) (5.0.4)
Requirement already satisfied: jsonschema>=3.0.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyterlab-server~=1.0.0->jupyterlab) (3.2.0)
Requirement already satisfied: json5 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyterlab-server~=1.0.0->jupyterlab) (0.9.1)
Requirement already satisfied: appnope; platform_system == "Darwin" in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipykernel->notebook>=4.3.1->jupyterlab) (0.1.0)
Requirement already satisfied: ipython>=5.0.0 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipykernel->notebook>=4.3.1->jupyterlab) (7.12.0)
Requirement already satisfied: entrypoints>=0.2.2 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (1.4.2)
Requirement already satisfied: mistune<2,>=0.8.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.8.4)
Requirement already satisfied: defusedxml in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.6.0)
Requirement already satisfied: testpath in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (0.4.4)
Requirement already satisfied: pygments in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (2.5.2)
Requirement already satisfied: bleach in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from nbconvert->notebook>=4.3.1->jupyterlab) (3.1.1)
Requirement already satisfied: python-dateutil>=2.1 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jupyter-client>=5.3.4->notebook>=4.3.1->jupyterlab) (2.8.1)
Requirement already satisfied: ptyprocess; os_name != "nt" in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from terminado>=0.8.1->notebook>=4.3.1->jupyterlab) (0.6.0)
Requirement already satisfied: decorator in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (4.4.1)
Requirement already satisfied: six in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages (from traitlets>=4.2.1->notebook>=4.3.1->jupyterlab) (1.12.0)
Requirement already satisfied: attrs>=17.4.0 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab) (19.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab) (1.5.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab) (0.15.7)
Requirement already satisfied: setuptools in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab) (40.8.0)
Requirement already satisfied: backcall in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.0)
Requirement already satisfied: jedi>=0.10 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.16.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (4.8.0)
Requirement already satisfied: pickleshare in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (3.0.3)
Requirement already satisfied: webencodings in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from bleach->nbconvert->notebook>=4.3.1->jupyterlab) (0.5.1)
Requirement already satisfied: zipp>=0.5 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema>=3.0.1->jupyterlab-server~=1.0.0->jupyterlab) (3.0.0)
Requirement already satisfied: parso>=0.5.2 in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from jedi>=0.10->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.6.1)
Requirement already satisfied: wcwidth in /Users/liweijun/Library/Python/3.7/lib/python/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.0.0->ipykernel->notebook>=4.3.1->jupyterlab) (0.1.8)
liweijun@liweijuns-MacBook-Pro pilot-student % jupyter lab
zsh: command not found: jupyter

```

[按照](https://www.jianshu.com/p/bdf6115339da)链接上的提示，使用pip3 show jupyter查找路径后，在/.zshrc中添加路径后，还是找不到
```
liweijun@liweijuns-MacBook-Pro pilot-student % pip3 show jupyter
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: jupyter
Version: 1.0.0
Summary: Jupyter metapackage. Install all the Jupyter components in one go.
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.org
License: BSD
Location: /Users/liweijun/Library/Python/3.7/lib/python/site-packages
Requires: jupyter-console, notebook, nbconvert, ipykernel, qtconsole, ipywidgets
Required-by: 
liweijun@liweijuns-MacBook-Pro pilot-student % source .zshrc
source: no such file or directory: .zshrc
liweijun@liweijuns-MacBook-Pro pilot-student % jupyter
zsh: command not found: jupyter
```

**Comment by Rhettup** [comment]
找到https://blog.csdn.net/xuaho0907/article/details/89450169
使用python3 -m IPython notebook打开了，但是不知道是什么原因呢？

**Comment by neolee** [comment]
你的环境肯定是有问题的，你执行下面的命令让我看看结果：

```shell
which python
which python3
python -V
python3 -V

pip -V
pip3 -V

brew doctor

echo $PATH
```

**Comment by Rhettup** [comment]
> 你的环境肯定是有问题的，你执行下面的命令让我看看结果：
> 
> ```shell
> which python
> which python3
> python -V
> python3 -V
> 
> pip -V
> pip3 -V
> 
> brew doctor
> 
> echo $PATH
> ```

**Comment by Rhettup** [comment]
不知道为啥版本又变了，我的Mac是新的，之前没有安装过东西
```
Last login: Sun Feb 23 17:26:06 on ttys000
liweijun@liweijuns-MacBook-Pro ~ % which python
/usr/bin/python
liweijun@liweijuns-MacBook-Pro ~ % which python3
/usr/local/bin/python3
liweijun@liweijuns-MacBook-Pro ~ % python -V
Python 2.7.16
liweijun@liweijuns-MacBook-Pro ~ % python3 -V
Python 3.7.6
liweijun@liweijuns-MacBook-Pro ~ % pip -V
pip 20.0.2 from /Users/liweijun/Library/Python/3.7/lib/python/site-packages/pip (python 3.7)
liweijun@liweijuns-MacBook-Pro ~ % pip3 -V
pip 20.0.2 from /Users/liweijun/Library/Python/3.7/lib/python/site-packages/pip (python 3.7)
liweijun@liweijuns-MacBook-Pro ~ % brew doctor
Your system is ready to brew.
liweijun@liweijuns-MacBook-Pro ~ % echo $PATH
/Users/liweijun/Library/Python/3.7/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by Rhettup** [comment]
现在使用ython3 -m IPython notebook这个命令又打不开了
```
liweijun@liweijuns-MacBook-Pro ~ % python3 -m IPython notebook
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/liweijun/Library/Python/3.7/lib/python/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/Users/liweijun/Library/Python/3.7/lib/python/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/Users/liweijun/Library/Python/3.7/lib/python/site-packages/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/Users/liweijun/Library/Python/3.7/lib/python/site-packages/traitlets/traitlets.py", line 57, in <module>
    import six
ModuleNotFoundError: No module named 'six'
liweijun@liweijuns-MacBook-Pro ~ % 
```

**Comment by neolee** [comment]
问题清楚了，你的系统里还有个 Python 环境，在 `/Users/liweijun/Library/Python/3.7` 下面。这里是不会凭空出现一个 Python 的，你一定装过什么。

结果导致你现在 `python3` 运行的是 Homebrew 安装的 Python（在 `/usr/local/` 下面），而 `pip` 和 `pip3` 都用的是上述不知道哪里来的 Python 环境里的，安装的包也在上述奇怪环境中。

解决办法：
1. 打开你的 `~/.bash_profile` 文件，找到类似 `export PATH=...` 这样的行，把其中 `/Users/liweijun/Library/Python/3.7/bin/` 的部分删掉，如果没把握就把整个 `.bash_profile` 文件给我看看，我告诉你怎么改；
2. 删掉 `/Users/liweijun/Library/Python` 整个目录。

然后再运行一遍前面我让你跑的命令：

```shell
which python
which python3
python -V
python3 -V

pip -V
pip3 -V

echo $PATH
```

如果一切无误，你以后就可以用 `python3` 来运行 Python 程序，用 `pip` 来安装 Python 包了。

**Comment by Rhettup** [comment]
code ~/.bash_profile
用以上命令打开后，文档里面是空的

**Comment by Rhettup** [comment]
应该是.zshrc中的，我删掉了

**Comment by neolee** [comment]
然后重开一个 Zsh Terminal，再来一次：

```shell
which python
which python3
python -V
python3 -V

pip -V
pip3 -V

echo $PATH
```

**Comment by Rhettup** [comment]
我把/Users/liweijun/Library/Python下面文件包含Python目录都删除了
```
liweijun@liweijuns-MacBook-Pro ~ % which python
/usr/bin/python
liweijun@liweijuns-MacBook-Pro ~ % which python3
/usr/local/bin/python3
liweijun@liweijuns-MacBook-Pro ~ % python -V
Python 2.7.16
liweijun@liweijuns-MacBook-Pro ~ % python3 -V
Python 3.7.6
liweijun@liweijuns-MacBook-Pro ~ % pip -V
zsh: command not found: pip
liweijun@liweijuns-MacBook-Pro ~ % pip3 -V
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
liweijun@liweijuns-MacBook-Pro ~ % echo $PATH
/Users/liweijun/Library/Python/3.7/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by Rhettup** [comment]
重新执行了pip3 install jupyterlab，pip install jupyterlab找不到，有执行了后面的命令，但是还有问题
```
liweijun@liweijuns-MacBook-Pro ~ % brew install node
Updating Homebrew...
Warning: node 13.8.0 is already installed and up-to-date
To reinstall 13.8.0, run `brew reinstall node`
liweijun@liweijuns-MacBook-Pro ~ % jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
```

**Comment by neolee** [comment]
不要着急啊，一步步来，还有几个问题：

1. 你还没把 `/Users/liweijun/Library/Python/3.7/bin/` 从 `~/.bash_profile` 或者 `.zshrc` 中删除，因为你现实的 `$PATH` 里还有，你刚才说你删掉了，看来没做对，我让你把整个文件给我看看的。

2. 从最新的信息来看，你现在 python3 和 pip3 这两个命令就是我们需要的环境里的正确命令了，所以从现在开始你可以用 `python3 ...` 来执行 Python 程序，用 `pip3 install ...` 或者 `python3 -m pip install ...` 来安装 Python 程序包了。

3. 从最后一条回复看，你的 Jupyter Lab 不是装好了么？你执行 `jupyter lab` 命令看看。

我一再说，学编程首先是学会和计算机交谈，知道你给它的命令是啥，理解它给你的反馈是啥，做事情专注细致不急躁。否则走不远。

**Comment by Rhettup** [comment]
谢谢您，我又检查了一下~/.bash_profile 和 ~/.zshrc 这两个文件目前都是空的，我又删了保存了一下，试了一遍那些命令结果还是一样的，还有可能是其他地方的问题吗？
我试了一下jupyter lab现在是可以用的。
以下是.zsh_history的内容不知道是否有用
```
xcode-select --install
pwd
ls
xcode-select --install
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
python3
ls
python hello.py
python hello.py
python3 hello.py
python3 hello.py
python3 hello.py
python3 hello.py
python3 hello.py
python3 hello.py
python3
python3 hello.py
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
curl
pwd
ls
curl
ruby brew_install.rb
ruby brew_install.rb
brew update
brew doctor
brew git
python3 -V
python3
brew git
git
code
code readme.txt
code downloads/
new termnial
new terminal
terminal
python
brew git
python3 -V
brew install git python
python3 -V
python
python3 -V
git
brew list
mkdir Code
cd Code
ls
code .
ls
python3 heloo.py
python3 hello.py
python3 hello.py
git clone https://github.com/Rhettup/pilot-student.git
cd pilot-student
ls
python -m pip install --upgrade pip
cd..
ls
cd..
cd..
pwd
cd
pwd
cd Code
cd
python -m pip install --upgrade pip
cd Code
ls
cd pilot-student
ls
pip install jupyterlab
cd
brew update
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install git python
python3 -V
cd Code
cd pilot-student
python -m pip install --upgrade pip
python -m ensurepip
python -m ensurepip --user
python -m pip install --upgrade pip
python -m pip install --upgrade pip --user
pip install jupyterlab
pip3 install jupyterlab
pip3 install jupyterlab --user
python -m pip install --upgrade pip --user
python -m pip3 install --upgrade pip3 --user
python -m pip3 install --upgrade pip --user
python -m pip install --upgrade pip3 --user
python -m pip install --upgrade pip --user
pip install --upgrade pip
python -m pip install --upgrade pip --user
pip install jupyterlab
pip3 install jupyterlab
brew install node
jupyter lab
pip3 install jupyterlab
jupyter lab
pip3 show jupyter
pip show jupyter
pip3 show jupyter
vim ~/.zshrc
vim ~/.zshrc
source .zshrc
vim ~/.zshrc
source .zshrc
jupyter lab
pip install jopyterlab
pip3 install jopyterlab
pip install --upgrade pip
python -m pip install --upgrade pip
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade pip --user
pip3 install jopyterlab
python3 -V
pip install jopyterlab
pip3 install jopyterlab
vim ~/.zshrc
pip3 install jopyterlab
python3 -m pip install -U pip
pip3 install jopyterlab
python3 -V
pip3 install jupyterlab --user
jupyter lab
jupyter lab --usr
jupyter lab --user
brew install node
jupyter lab
pip3 install jupyterlab
jupyterlab
jupyter lab
ls
find -name jupyter
pip3 show jupyter
pip3 show jupyter --user
pip3 show jupyter lab
pip3 install --upgrade pip
pip3 install jupyter
jubyter
jupyter
pip3 show jupyter
pip3 show jupyterlab
vim ~/.zshrc
jupyter
source .zshrc
vim ~/.zshrc
vim ~/.zshrc
source .zshrc
vim ~/.zshrc
source .zshrc
pip3 show jupyter
jupyter
jupyterlab
pip3 show jupyter
python3 -m IPython notebook
quit
exit
ls
cd Code
ls
cd pilot-student
ls
python3 -m IPython notebook
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
brew doctor
echo $PATH
python3 -m IPython notebook

```
