### ISSUE TITLE
python -m pip install --upgrade pip 不成功

### ISSUE THREAD

**Issue by wangxsh06** [neolee/pilot#1161]
今天昨天试了很多次，都提示以下相同的错误，只不过下载进度条不一样。（我可以直接登录网址下载这个文件）

PS C:\Users\wangxx95\Code\pilot-student> python -m pip install --upgrade pip
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/pip/
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
     |██                              | 81kB 2.4kB/s eta 0:09:16ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 397, in _error_catcher
    yield
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 479, in read
    data = self._fp.read(amt)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 924, in unpack_http_url
    progress_bar)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\hashes.py", line 75, in check_against_chunks

    for chunk in chunks:
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 829, in written_chunks
    for chunk in chunks:
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\ui.py", line 156, in iter
    for x in it:
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 818, in resp_read
    decode_content=False):
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\wangxx95\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 402, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by neolee** [comment]
网络问题。

如果别的都装好了，只是 pip install 的问题的话，可以尝试使用国内的 PyPi 镜像，比如清华的：

https://mirror.tuna.tsinghua.edu.cn/help/pypi/
