### ISSUE TITLE
安装 jupylab 时，安装到一半出错的问题

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1246]
安装到这一步的一半时出现问题，Collecting pywin32>=1.0; sys_platform == "win32"
  Downloading pywin32-227-cp37-cp37m-win_amd64.whl (9.1 MB)

问题如下；
Traceback (most recent call last):
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\33176\scoop\apps\python37\current\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "c:\users\33176\scoop\apps\python37\current\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "c:\users\33176\scoop\apps\python37\current\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\33176\scoop\apps\python37\current\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\33176\scoop\apps\python37\current\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 282, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    hashes=hashes,
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 287, in unpack_url
    hashes=hashes,
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 159, in unpack_http_url
    link, downloader, temp_dir.path, hashes
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 303, in _download_http_url
    for chunk in download.chunks:
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\ui.py", line 160, in iter
    for x in it:
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_internal\network\utils.py", line 39, in response_chunks
    decode_content=False,
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\33176\scoop\apps\python37\current\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\33176\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by neolee** [comment]
网络问题。

如果 Python 本身已经确认安装好，可以尝试使用国内镜像来安装 Python 的各种第三方软件，本仓库的 Wiki 里有方法。

**Comment by LFN3399** [comment]
既然是网络问题，可以从新安装吗？怎么操作呢？再不行再用第三方软件。

**Comment by neolee** [comment]
你当然可以重试啊。

对于装 JupyterLab 这种任务，使用国内镜像是非常安全可靠的方案。

**Comment by LFN3399** [comment]
我试着用镜像的方法安装，前面安装了一半的要怎么卸载呢或删除呢？

**Comment by neolee** [comment]
没啥错误的话就直接装就行。

**Comment by LFN3399** [comment]
老师我用镜像安装时出现这样的情况，是表示要在某个地方新建安装地址吗？
PS C:\Users\33176\Code\pilot-student> pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
Writing to C:\Users\33176\AppData\Roaming\pip\pip.ini

**Comment by neolee** [comment]
没啥问题啊，接着安装就好了啊。

**Comment by LFN3399** [comment]
以下是安装命令，就差   ’临时使用‘ 这行没有试过，下面三行都试了，安装情况如最下面部分，这样要怎么操作呢？

pypi 镜像使用帮助
pypi 镜像每 5 分钟同步一次。

临时使用
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple some-package
注意，simple 不能少, 是 https 而不是 http

设为默认
升级 pip 到最新的版本 (>=10.0.0) 后进行配置：

pip install pip -U
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
如果您到 pip 默认源的网络连接较差，临时使用本镜像站来升级 pip：
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U

 


PS C:\Users\33176\Code\pilot-student> pip install pip -U
Requirement already up-to-date: pip in c:\users\33176\scoop\apps\python37\current\lib\site-packages (20.0.2)
PS C:\Users\33176\Code\pilot-student> pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
Writing to C:\Users\33176\AppData\Roaming\pip\pip.ini
PS C:\Users\33176\Code\pilot-student> pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already up-to-date: pip in c:\users\33176\scoop\apps\python37\current\lib\site-packages (20.0.2)
PS C:\Users\33176\Code\pilot-student>

**Comment by neolee** [comment]
第一，你前面运行了 `pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple` 之后就已经是默认使用清华的镜像站了，后面只需要简单地 `pip install <你要安装的包>` 就可以了。

第二，你运行 `pip install -U pip` 就是安装/更新 `pip` 这个包，然后系统告诉你，已经是最新版本了。

所以你下面就继续装 JupyterLab 就好了呀，命令就是 `pip install jupyterlab`。

**Comment by LFN3399** [comment]
老师 以下显示代表 jupyterlab 安装成功了吗？
 Installing collected packages: MarkupSafe, jinja2, pywin32, decorator, six, ipython-genutils, traitlets, jupyter-core, pyrsistent, zipp, importlib-metadata, attrs, jsonschema, nbformat, tornado, python-dateutil, pyzmq, jupyter-client, wcwidth, prompt-toolkit, pickleshare, backcall, colorama, parso, jedi, pygments, ipython, ipykernel, pywinpty, terminado, prometheus-client, mistune, defusedxml, pandocfilters, webencodings, bleach, entrypoints, testpath, nbconvert, Send2Trash, notebook, json5, jupyterlab-server, jupyterlab
    Running setup.py install for pyrsistent ... done
    Running setup.py install for backcall ... done
    Running setup.py install for prometheus-client ... done
    Running setup.py install for pandocfilters ... done
Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 backcall-0.1.0 bleach-3.1.3 colorama-0.4.3 decorator-4.4.2 defusedxml-0.6.0 entrypoints-0.3 importlib-metadata-1.5.0 ipykernel-5.2.0 ipython-7.13.0 ipython-genutils-0.2.0 jedi-0.16.0 jinja2-2.11.1 json5-0.9.3 jsonschema-3.2.0 jupyter-client-6.1.0 jupyter-core-4.6.3 jupyterlab-2.0.1 jupyterlab-server-1.0.7 mistune-0.8.4 nbconvert-5.6.1 nbformat-5.0.4 notebook-6.0.3 pandocfilters-1.4.2 parso-0.6.2 pickleshare-0.7.5 prometheus-client-0.7.1 prompt-toolkit-3.0.4 pygments-2.6.1 pyrsistent-0.15.7 python-dateutil-2.8.1 pywin32-227 pywinpty-0.5.7 pyzmq-19.0.0 six-1.14.0 terminado-0.8.3 testpath-0.4.4 tornado-6.0.4 traitlets-4.3.3 wcwidth-0.1.9 webencodings-0.5.1 zipp-3.1.0
PS C:\Users\33176\Code\pilot-student>

**Comment by neolee** [comment]
你觉得呢？

努力去读和猜计算机对你说啥了，然后，胆子放大一点，没事儿的……

**Comment by LFN3399** [comment]
我翻译过来就是安装成功了好多个程序， 现在输入 jupyter lab 可以打开网页了，谢谢老师

**Comment by neolee** [comment]
勇敢的前进吧！
