### ISSUE TITLE
启动 Jupyter Lab 的服务程序有问题

### ISSUE THREAD

**Issue by beihaichenxiong** [neolee/pilot#228]
PS C:\Users\lenovo\code\pilot-student> jupyter lab
Traceback (most recent call last):
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lenovo\scoop\apps\python37\current\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lenovo\scoop\apps\python37\current\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\scoop\apps\python37\current\scripts\jupyter-lab.EXE\__main__.py", line 4, in <module>
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\labapp.py", line 40, in <module>
    app_version = get_app_version()
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 541, in get_app_version
    app_options, app_dir=app_dir, core_config=core_config))
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 582, in __init__
    self.registry = options.registry
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 343, in _default_registry
    config = _yarn_config(self.logger)["yarn config"]
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 1765, in _yarn_config
    node = which('node')
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab_server\process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
PS C:\Users\lenovo\code\pilot-student>

**Comment by beihaichenxiong** [comment]
PS C:\Users\lenovo\code\pilot-student> jupyter lab
Traceback (most recent call last):
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\lenovo\scoop\apps\python37\current\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lenovo\scoop\apps\python37\current\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lenovo\scoop\apps\python37\current\scripts\jupyter-lab.EXE\__main__.py", line 4, in <module>
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\labapp.py", line 40, in <module>
    app_version = get_app_version()
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 541, in get_app_version
    app_options, app_dir=app_dir, core_config=core_config))
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 582, in __init__
    self.registry = options.registry
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 343, in _default_registry
    config = _yarn_config(self.logger)["yarn config"]
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab\commands.py", line 1765, in _yarn_config
    node = which('node')
  File "c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab_server\process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
PS C:\Users\lenovo\code\pilot-student> jupyer lab
jupyer : 无法将“jupyer”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ jupyer lab
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo\code\pilot-student> jupyer lab
jupyer : 无法将“jupyer”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ jupyer lab
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo\code\pilot-student>

**Comment by beihaichenxiong** [comment]
不知道出现了什么问题。

**Comment by neolee** [comment]
后面几个错误是你拼错了 jupyter。

前面的错误是 jupyter lab 运行出错了，看上去是个很久前的 bug。请你执行下面的几个命令给我看看结果：

```powershell
python -V
pip -V
pip list
jupyter --version
```

**Comment by neolee** [comment]
另外，试试先安装 nodejs：`scoop install nodejs`，然后在尝试 `jupyter lab`。

**Comment by logdazy** [comment]
> 另外，试试先安装 nodejs：`scoop install nodejs`，然后在尝试 `jupyter lab`。

搞定了，谢谢李老师

**Comment by beihaichenxiong** [comment]
PS C:\Users\lenovo> scoop install nodejs
Updating Scoop...
Updating 'main' bucket...
 * 15a9f903 trid: Update to version 2.24-19.10.30                        55 minutes ago
 * 59719e01 ffmpeg-nightly: Update to version 20191029-d3dee67           4 hours ago
 * ff92cc2e helmfile: Update to version 0.90.1                           5 hours ago
 * d55d8294 latex: Use arch-spec 'env_add_path' (#518)                   7 hours ago
 * d0318399 jx: Update to version 2.0.927                                12 hours ago
 * 79ca9444 aws-vault: Update to version 4.7.1                           12 hours ago
 * 8e60164c minikube: Update to version 1.5.1                            13 hours ago
 * 081314ff k9s: Update to version 0.9.3                                 13 hours ago
 * c20097fb jcli: Update to version 0.0.22                               13 hours ago
 * b34e4302 vim: Update to version 8.1.2233                              14 hours ago
 * 3b14f427 helm: Update to version 2.15.2                               16 hours ago
 * 50da6919 aws: Update to version 1.16.269                              16 hours ago
 * 362a8820 jx: Update to version 2.0.923                                20 hours ago
 * 9d95df93 1password-cli: Update to version 0.7.1                       22 hours ago
Updating 'versions' bucket...
 * e4cddc4 gitversion-beta: Update to version 5.1.2-beta1-1              14 hours ago
Scoop was updated successfully!
Installing 'nodejs' (13.0.1) [64bit]
node-v13.0.1-win-x64.7z (15.6 MB) [==================================================================================================================] 100%
Checking hash of node-v13.0.1-win-x64.7z ... ok.
Extracting node-v13.0.1-win-x64.7z ... done.
Linking ~\scoop\apps\nodejs\current => ~\scoop\apps\nodejs\13.0.1
Persisting bin
Persisting cache
Running post-install script...
'nodejs' (13.0.1) was installed successfully!
PS C:\Users\lenovo> python -V
Python 3.7.4
PS C:\Users\lenovo> pip -V
pip 19.3.1 from c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\pip (python 3.7)
PS C:\Users\lenovo> pip list
Package            Version
------------------ -------
attrs              19.3.0
backcall           0.1.0
bleach             3.1.0
colorama           0.4.1
decorator          4.4.1
defusedxml         0.6.0
entrypoints        0.3
importlib-metadata 0.23
ipykernel          5.1.3
ipython            7.9.0
ipython-genutils   0.2.0
jedi               0.15.1
Jinja2             2.10.3
json5              0.8.5
jsonschema         3.1.1
jupyter-client     5.3.4
jupyter-core       4.6.1
jupyterlab         1.2.0
jupyterlab-server  1.0.6
MarkupSafe         1.1.1
mistune            0.8.4
more-itertools     7.2.0
nbconvert          5.6.1
nbformat           4.4.0
notebook           6.0.1
pandocfilters      1.4.2
parso              0.5.1
pickleshare        0.7.5
pip                19.3.1
prometheus-client  0.7.1
prompt-toolkit     2.0.10
Pygments           2.4.2
pyrsistent         0.15.5
python-dateutil    2.8.0
pywin32            225
pywinpty           0.5.5
pyzmq              18.1.0
Send2Trash         1.5.0
setuptools         40.8.0
six                1.12.0
terminado          0.8.2
testpath           0.4.2
tornado            6.0.3
traitlets          4.3.3
wcwidth            0.1.7
webencodings       0.5.1
zipp               0.6.0
PS C:\Users\lenovo> jupyter --version
jupyter core     : 4.6.1
jupyter-notebook : 6.0.1
qtconsole        : not installed
ipython          : 7.9.0
ipykernel        : 5.1.3
jupyter client   : 5.3.4
jupyter lab      : 1.2.0
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 4.4.0
traitlets        : 4.3.3
PS C:\Users\lenovo>

**Comment by beihaichenxiong** [comment]
搞定了。谢谢大家。
