### ISSUE TITLE
macOS Catalina 安装 jupyterlab 出现 DEPRECATION: Python 2.7 will reach the end of its life...

### ISSUE THREAD

**Issue by sunyan023** [neolee/pilot#26]
以下是terminal显示
192:~ sunny$ pip install jupyterlab
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting jupyterlab
  Downloading https://files.pythonhosted.org/packages/1b/1b/ce43d66010878f86e574ae94d4aa6f78028ba5dba7287e11ebbaea2b3c17/jupyterlab-0.33.12-py2.py3-none-any.whl (14.3MB)
     |▎                               | 112kB 7.3kB/s eta 0:32:39ERROR: Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
192:~ sunny$

**Comment by neolee** [comment]
请你运行下面几个命令，把结果截给我看看：

```shell
brew doctor
brew update

which python
which python3
which pip
which pip3
```

**Comment by sunyan023** [comment]
update那行没反应我就退出来了

**Comment by sunyan023** [comment]
![BB46C3D5-FA3E-4156-9549-E66CE22C723E](https://user-images.githubusercontent.com/55344702/67390954-386a3d00-f5d0-11e9-96a3-6da115826e94.jpeg)
![Uploading F0A30857-BC28-4DE7-A24F-8E1485DB1AFD.jpeg…]()

**Comment by neolee** [comment]
先不管 brew update，这个需要联网，先把后面四个运行一下，结果给我看看。

**Comment by sunyan023** [comment]
Last login: Wed Oct 23 19:49:33 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
192:~ sunny$ which python
/usr/bin/python
192:~ sunny$ which python3
/usr/local/bin/python3
192:~ sunny$ which pip
/usr/local/bin/pip
192:~ sunny$ which pip3
/usr/local/bin/pip3
192:~ sunny$

**Comment by neolee** [comment]
好的，继续，运行下面几个命令，给我看看结果：

```shell
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by sunyan023** [comment]
Last login: Wed Oct 23 19:51:06 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
192:~ sunny$ python -V
Python 2.7.16
192:~ sunny$ python3 -V
Python 3.7.4
192:~ sunny$ pip -V
pip 19.3.1 from /Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip (python 2.7)
192:~ sunny$ pip3 -V
pip 19.3.1 from /Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg/pip (python 2.7)
192:~ sunny$

**Comment by neolee** [comment]
为什么你的 pip 和 pip3 都在 /usr/local/bin 下面（应该来自 Homebrew 安装），指向的库却在系统自带的老 Python 2.7 呢？

你是严格按照 [环境配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 用 Homebrew 安装的 Python 3.7.4 吗？

**Comment by neolee** [comment]
请你执行下面两个命令，把结果截给我看：

```shell
cd /usr/local/bin
ls -l pip* python*
```

**Comment by sunyan023** [comment]
192:~ sunny$ cd /usr/local/bin
192:bin sunny$ ls -l pip* python*
-rwxr-xr-x  1 root   admin  448 10 23 11:40 pip
-rwxr-xr-x  1 root   admin  450 10 23 11:40 pip3
-rwxr-xr-x  1 root   admin  454 10 23 11:40 pip3.7
lrwxr-xr-x  1 sunny  admin   36 10 23 10:22 python3 -> ../Cellar/python/3.7.4_1/bin/python3
lrwxr-xr-x  1 sunny  admin   43 10 23 10:22 python3-config -> ../Cellar/python/3.7.4_1/bin/python3-config
lrwxr-xr-x  1 sunny  admin   38 10 23 10:22 python3.7 -> ../Cellar/python/3.7.4_1/bin/python3.7
lrwxr-xr-x  1 sunny  admin   45 10 23 10:22 python3.7-config -> ../Cellar/python/3.7.4_1/bin/python3.7-config
lrwxr-xr-x  1 sunny  admin   39 10 23 10:22 python3.7m -> ../Cellar/python/3.7.4_1/bin/python3.7m
lrwxr-xr-x  1 sunny  admin   46 10 23 10:22 python3.7m-config -> ../Cellar/python/3.7.4_1/bin/python3.7m-config
192:bin sunny$

**Comment by neolee** [comment]
你似乎以前用别的方法安装过 Python 2.x，所以上面的几个 pip 文件的 owner 是 root，于是 Homebrew 安装时无法覆盖这些文件，所以环境目前是乱的。

你能不能回忆起之前是怎么安装 Python 2.x 的？最好将其完整清除，然后再用 Homebrew 重装一次 python。

也有比较粗暴的办法，尝试依次执行下面的命令：

```shell
cd /usr
sudo chown -R sunny:admin local
brew uninstall python
brew install python
```

**Comment by neolee** [comment]
这个只要不报错，就是在更新 Homebrew，等吧。

**Comment by neolee** [comment]
你前面的 `sudo chown -R sunny:admin local` 应该没有运行成功，因为报了 `chown: local: Operation not permitted`。

等下应该还是有问题的。

**Comment by neolee** [comment]
你先按 Control+C 中断执行，然后重新运行下这几个命令：

```shell
cd /usr/local
sudo chown -R sunny:admin *
brew install python
```

**Comment by Jared-Gong** [comment]
老师 我早上安装jupyterlab也遇到了类似的问题，请问需要怎么解决呢？
![1571881954(1)](https://user-images.githubusercontent.com/56901849/67446855-8a4caa80-f644-11e9-877f-4f77edf10235.png)

**Comment by neolee** [comment]
@Jared-Gong 你这个是网络问题，多试试吧。

**Comment by Jared-Gong** [comment]
> @Jared-Gong 你这个是网络问题，多试试吧。
![1571891666(1)](https://user-images.githubusercontent.com/56901849/67453899-c4c14200-f65a-11e9-848b-d657fbfeca49.png)
老师  安装中出现了以上报错，是要重下载吗？

**Comment by neolee** [comment]
@Jared-Gong 你这个是别的问题，请你重新开一个 issue。

**Comment by zhangSen1987** [comment]
> @Jared-Gong 你这个是网络问题，多试试吧。

老师  这个安装 需要开VPN吧，下载速度是几KB/s 然后就显示这个错误了

**Comment by neolee** [comment]
@zhangSen1987 如果网络不好最好开代理。另外这个 issue 的原问题已经解决，有其他问题请开新 issue。

**Comment by neolee** [comment]
@sunyan023 帮你贴一下

```
192:usr sunny$ cd /usr/local
192:local sunny$ sudo chown -R sunny:admin *
192:local sunny$ brew install python
Updating Homebrew...
Warning: python 3.7.4_1 is already installed and up-to-date
To reinstall 3.7.4_1, run brew reinstall python
192:local sunny$
```

这样的话，你就运行 `brew reinstall python` 试试。

**Comment by sunyan023** [comment]
麻烦看一下，这是运行brew reinstall python后的显示：
192:local sunny$ brew reinstall python
==> Reinstalling python 
==> Downloading https://homebrew.bintray.com/bottles/python-3.7.4_1.catalina.bot
Already downloaded: /Users/sunny/Library/Caches/Homebrew/downloads/1950aa3ee7562c8f28bc45dc2f27c5a7a2e5b864afd5818f3e7cc55ca24499d4--python-3.7.4_1.catalina.bottle.1.tar.gz
==> Pouring python-3.7.4_1.catalina.bottle.1.tar.gz
==> /usr/local/Cellar/python/3.7.4_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.4_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.4_1/bin/python3 -s setup.py --no-user-cfg insta
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.7.4_1: 3,958 files, 60.7MB
192:local sunny$

**Comment by sunyan023** [comment]
好像还是有点问题
192:local sunny$ python3 -V
Python 3.7.4
192:local sunny$ pip3 -V
pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
192:local sunny$ pip3 install -U pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
     |▊                               | 30kB 1.4kB/s eta 0:16:55ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 397, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 479, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 188, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 359, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 307, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 199, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 1064, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 924, in unpack_http_url
    progress_bar)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 1152, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 861, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 75, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 829, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 156, in iter
    for x in it:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 818, in resp_read
    decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 531, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 496, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 402, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
192:local sunny$ pip3 install jupyterla
Collecting jupyterla
  ERROR: Could not find a version that satisfies the requirement jupyterla (from versions: none)
ERROR: No matching distribution found for jupyterla

ç192:local sunny$ 
192:local sunny$ ç
192:local sunny$ cd Code
-bash: cd: Code: No such file or directory
192:local sunny$ mkdir Code
mkdir: Code: Permission denied
192:local sunny$

**Comment by neolee** [comment]
前面运行 `pip3 install -U pip` 因为网络问题没有成功完成。

而后面安装 jupyterlab 的命令输错了。

不要急，慢慢来，看清楚自己输入了什么，知道自己在做啥，也学会了解计算机说了啥，不然就是浪费时间。

**Comment by sunyan023** [comment]
运行好几次这个命令，但还是出现一片红色，肿么办？我去复制粘贴网址下载可行吗？
192:local sunny$ pip3 install -U pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 397, in _error_catcher

**Comment by neolee** [comment]
这个是网络的问题，试试换别的网络或者代理。

**Comment by sunyan023** [comment]
pip安装好啦，耶✌️，但jupyterlab好像有点问题，这次没漏字母了，嘻嘻
Successfully installed pip-19.3.1
192:local sunny$ pip3 install jupyterlab
Collecting jupyterlab
  Downloading https://files.pythonhosted.org/packages/2c/89/a4e048f198867f19d2a9f40d08c946d760ab06dd39d774940a20da47b5f9/jupyterlab-1.1.4-py2.py3-none-any.whl (15.3MB)
     |█████████                       | 4.3MB 4.4kB/s eta 0:41:15ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 457, in read
    n = self.readinto(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
192:local sunny$

**Comment by neolee** [comment]
还是网络问题，不过看着几乎快玩成了，应该再试试就行了。

**Comment by sunyan023** [comment]
jupyter lab的界面打开了，但双击notebook下方的python3却显示：Invalid response: 403 Forbidden，是什么情况呢

**Comment by neolee** [comment]
把运行 jupyter lab 的命令行窗口和报错的浏览器窗口都截屏发过来。

**Comment by sunyan023** [comment]
ok了，好了，应该又是网络问题，麻烦了，谢谢
