### ISSUE TITLE
Mac 环境执行 jupiter lab 出现问题

### ISSUE THREAD

**Issue by vhanmeng** [neolee/pilot#269]
hanmengdeMacBook-Pro:~ hanmeng$ jupyter lab
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labapp.py", line 40, in <module>
    app_version = get_app_version()
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 541, in get_app_version
    app_options, app_dir=app_dir, core_config=core_config))
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 582, in __init__
    self.registry = options.registry
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 343, in _default_registry
    config = _yarn_config(self.logger)["yarn config"]
  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1765, in _yarn_config
    node = which('node')
  File "/usr/local/lib/python3.7/site-packages/jupyterlab_server/process.py", line 59, in which
    raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

**Comment by neolee** [comment]
需要安装 nodejs：`brew install node`
