### ISSUE TITLE
安装 python -m pip install --upgrade pip 出现问题。

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#360]
You are using pip version 19.0.3, however version 19.3.1 is available.
这种情况应该怎么处理？

PS C:\Users\90522> cd code
PS C:\Users\90522\code> git clone https://github.com/zhipingyang120/pilot-student.git
Cloning into 'pilot-student'...
remote: Enumerating objects: 32, done.
remote: Total 32 (delta 0), reused 0 (delta 0), pack-reused 32
  71% (23/32)
Unpacking objects: 100% (32/32), done.
PS C:\Users\90522\code> cd pilot-student
PS C:\Users\90522\code\pilot-student> python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
    39% |████████████▌                   | 552kB 9.4kB/s eta 0:01:3
    39% |█████████████                   | 563kB 8.8kB/s eta 0:01:3
    41% |█████████████                   | 583kB 8.9kB/s eta 0:01:3
    41% |█████████████▌                  | 593kB 6.2kB/s eta 0:02:
    42% |█████████████▌                  | 604kB 6.4kB/s eta 0:02:
    43% |██████████████                  | 614kB 7.1kB/s eta 0:01:
    44% |██████████████                  | 624kB 6.5kB/s eta 0:02:
    44% |██████████████▌                 | 634kB 7.2kB/s eta 0:01
    45% |██████████████▌                 | 645kB 6.0kB/s eta 0:02
    46% |███████████████                 | 655kB 5.6kB/s eta 0:02
    47% |███████████████                 | 665kB 5.8kB/s eta 0:02
    47% |███████████████                 | 675kB 6.1kB/s eta 0:02
    48% |███████████████▌                | 686kB 5.6kB/s eta 0:0
    49% |████████████████                | 696kB 7.6kB/s eta 0:0
    49% |████████████████                | 706kB 6.9kB/s eta 0:0
    50% |████████████████                | 716kB 7.2kB/s eta 0:0
    51% |████████████████▌               | 727kB 7.2kB/s eta 0:
    52% |█████████████████               | 737kB 7.7kB/s eta 0:
    52% |█████████████████               | 747kB 9.2kB/s eta 0:
    53% |█████████████████               | 757kB 11kB/s eta 0:0
    54% |█████████████████▌              | 768kB 9.4kB/s eta 0
    54% |█████████████████▌              | 778kB 9.6kB/s eta 0
    55% |██████████████████              | 788kB 10.0kB/s eta
    56% |██████████████████              | 798kB 11kB/s eta 0:
    57% |██████████████████              | 808kB 11kB/s eta 0:
    57% |██████████████████▌             | 819kB 10kB/s eta 0
    58% |███████████████████             | 829kB 10.0kB/s eta
    59% |███████████████████             | 839kB 8.0kB/s eta
    60% |███████████████████             | 849kB 7.7kB/s eta
    60% |███████████████████▌            | 860kB 8.1kB/s eta
    61% |████████████████████            | 870kB 8.9kB/s eta
    62% |████████████████████            | 880kB 8.2kB/s eta
    62% |████████████████████            | 890kB 10kB/s eta
    63% |████████████████████▌           | 901kB 9.4kB/s et
    64% |████████████████████▌           | 911kB 8.9kB/s et
    65% |█████████████████████           | 921kB 9.7kB/s et
    65% |█████████████████████           | 931kB 10kB/s eta
    66% |█████████████████████           | 942kB 13kB/s eta
    67% |█████████████████████▌          | 952kB 13kB/s et
    68% |██████████████████████          | 962kB 5.4kB/s e
ta 0:01:24Exception:
Traceback (most recent call last):
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 360, in _error_catcher
    yield
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\90522\scoop\apps\python37\current\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "C:\Users\90522\scoop\apps\python37\current\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\90522\scoop\apps\python37\current\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\90522\scoop\apps\python37\current\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\90522\scoop\apps\python37\current\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\cli\base_command.py", line 179, in main
    status = self.run(options, args)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 334, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 878, in unpack_url
    progress_bar=progress_bar
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 702, in unpack_http_url
    progress_bar)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 946, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 639, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\hashes.py", line 62, in check_against_chunks
    for chunk in chunks:
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 607, in written_chunks
    for chunk in chunks:
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\ui.py", line 159, in iter
    for x in it:
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 596, in resp_read
    decode_content=False):
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 459, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "C:\Users\90522\scoop\apps\python37\current\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\90522\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
**You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.**

**Comment by neolee** [comment]
网络的问题，再试试，或者换网络或挂代理试试。
