### ISSUE TITLE
Error Starting Kernel

### ISSUE THREAD

**Issue by qixinsame** [neolee/pilot#429]
问题复现：
1. 从powershell 命令行中正常启动Jupyter lab, 执行命令如下：

- cd Code
- cd pilot-student
- jupyter lab

2. 成功启动Jupyter lab浏览器页面（Chrome）
3. 双击打开任一章节ipynb文件
4. 出现弹窗如下要求“Select Kernel”
<img width="958" alt="1" src="https://user-images.githubusercontent.com/43022624/68396218-28e01c00-01ac-11ea-9c7d-037da534ba96.PNG">
5.点开下拉菜单选项，选项如下：
<img width="595" alt="2" src="https://user-images.githubusercontent.com/43022624/68396292-4b723500-01ac-11ea-96b2-c006adc1e02e.PNG">
6.选择任一选项（包括默认选项Python3），均提示Error Starting Kernel如下
<img width="412" alt="3" src="https://user-images.githubusercontent.com/43022624/68396345-63e24f80-01ac-11ea-9e5d-82904dfd17b6.PNG">
7.点击OK后可以正常打开学习用书，但是右上角提示“No Kernel！”

书中代码只能输入，不能运行

**Comment by neolee** [comment]
似乎是 Python 没装好。

**Comment by qixinsame** [comment]
@neolee 

1. 我当时按照配置指南安装的时候提示是安装成功的。
2. 我用Scoop list 命令看了下也是显示如下
3. 试着直接在powershell里面run python也是可成功运行的
<img width="479" alt="4" src="https://user-images.githubusercontent.com/43022624/68528553-51dcea00-032f-11ea-9386-cd066b582db4.PNG">
整个安装环节过程中也没有报错，所以现在也不知道该如何处理。

4. 在Google搜索“Error starting Kernel”,在Jupyter的官方Github页面里也看到有类似的Issue，但是大家的fix都是运行以个命令“python -m ipykernel install --user”我以照着安装了，也提示成功了，截图如下。但是我的问题还是没有解决，也没有任何变化。所以还是想继续问问李老师有没有其他的办法可以尝试解决？
<img width="506" alt="5" src="https://user-images.githubusercontent.com/43022624/68528624-24dd0700-0330-11ea-90cc-145890f199a6.PNG">

**Comment by neolee** [comment]
`python -m ipykernel install --user` 这个没啥用的。因为你已经可以从列表里选择 Python 3 这个 kernel，说明这个 kernel 已经成功注册到 Jupyter Lab 了，你的问题是启动这个 kernel 的时候运行出错（注意你一楼的最后一个截图里 `DLL load failed` 是关键错误信息）。

现在不知道具体是哪里出错，比较像是某个 Windows 的 DLL 有点问题。

**Comment by qixinsame** [comment]
@neolee 谢谢老师耐心解答。那这个是要重装Windows的节奏吗？我这是台刚买连个月的Thinkpad，安装的也都是正版软件。或者是因为我是Windows 10 家庭中文版的原因吗？

**Comment by neolee** [comment]
不用，关键要找到哪里出了问题，你可以把选 Python 3 作为 kernel 之后出错的完整信息发上来吗？

**Comment by qixinsame** [comment]
@neolee 拷贝了全部的“Error Message”如下

Traceback (most recent call last):
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\jupyter_client\connect.py", line 476, in write_connection_file
    kernel_name=self.kernel_name
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "c:\users\qixin\scoop\apps\python37\current\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\jupyter_core\paths.py", line 424, in secure_write
    win32_restrict_file_to_user(fname)
  File "c:\users\qixin\scoop\apps\python37\current\lib\site-packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: 找不到指定的程序。

**Comment by neolee** [comment]
我用 "jupyter error starting kernel import win32api dll load failed" 作为关键词 Google 搜索，有不少相关的页面，但似乎很多和 Anaconda 有关，具体来说是 Anaconda 和原生 Python 使用的一个 Windows 接口 DLL 的冲突有关。所以你之前有安装过 Anaconda？

另外，请你执行一下下面的命令让我了解下你的本地环境版本：

```powershell
which python
pip -V
jupyter --version
```

**Comment by qixinsame** [comment]
1.对的，我之前确实安装过Anaconda
2.本地环境版本如下：
<img width="662" alt="6" src="https://user-images.githubusercontent.com/43022624/68543852-65ec1e80-03f7-11ea-856e-7303dd003f3b.PNG">

**Comment by neolee** [comment]
也许这个对你有帮助： https://github.com/jupyter/notebook/issues/4909

里面提到 Anaconda 的一个 bug： https://github.com/conda-forge/jupyter_client-feedstock#installing-jupyter_client

这也是为什么我很不喜欢 Anaconda 的原因，它相当于在 Python 环境之外自己搞了一套，很多东西差不多，但是不知道什么时候会碰到一个他们改过的东西不兼容或者干脆不 work……

**Comment by qixinsame** [comment]
补充：问题通过完全卸载Anaconda得到了完美的解决。为了将Anaconda卸载干净，需要先安装Anaconda-Clean package。以下链接中有如何“完全”卸载Anaconda的步骤

https://docs.anaconda.com/anaconda/install/uninstall/
