### ISSUE TITLE
pip install jupyterlab 出错

### ISSUE THREAD

**Issue by kobeyyn** [neolee/pilot#535]
ERROR: Could not find a version that satisfies the requirement traitlets>=4.2.1 (from notebook>=4.3.1->jupyterlab) (from versions: none)
ERROR: No matching distribution found for traitlets>=4.2.1 (from notebook>=4.3.1->jupyterlab)

**Comment by neolee** [comment]
你执行下下面的命令：

```shell
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by kobeyyn** [comment]
PS C:\Users\Administrator> which python
C:/Users/Administrator/scoop/shims/python.exe
PS C:\Users\Administrator> which python3
C:/Users/Administrator/scoop/shims/python3.exe
PS C:\Users\Administrator> python -V
Python 3.7.4
PS C:\Users\Administrator> python3 -V
Python 3.7.4
PS C:\Users\Administrator> pip -V
pip 19.3.1 from c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip (python 3.7)
PS C:\Users\Administrator> pip3 -V
pip 19.3.1 from c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip (python 3.7)
PS C:\Users\Administrator>

**Comment by neolee** [comment]
环境是没问题的，可能是 `pip install jupyterlab` 过程中有意外发生（正常是不会出现你这个问题的），可以重试下。

**Comment by kobeyyn** [comment]
PS C:\Users\Administrator> python -m pip install --upgrade pip
Requirement already up-to-date: pip in c:\users\administrator\scoop\apps\python37\current\lib\site-packages (19.3.1)
PS C:\Users\Administrator> pip install jupyterlab
Collecting jupyterlab
  Using cached https://files.pythonhosted.org/packages/eb/94/cd9e53b9d3e4c35202dec30e1b623c355bd9de2b0c53e1bc7f4af31d25d8/jupyterlab-1.2.3-py2.py3-none-any.whl
Collecting tornado!=6.0.0,!=6.0.1,!=6.0.2
  Using cached https://files.pythonhosted.org/packages/35/2e/ce3f7426ee077fa376facfc9aa3fc83f9dd3d0281270e95864efd8ba6f77/tornado-6.0.3-cp37-cp37m-win32.whl
Collecting jinja2>=2.10
  Using cached https://files.pythonhosted.org/packages/65/e0/eb35e762802015cab1ccee04e8a277b03f1d8e53da3ec3106882ec42558b/Jinja2-2.10.3-py2.py3-none-any.whl
Collecting jupyterlab-server~=1.0.0
  Using cached https://files.pythonhosted.org/packages/78/98/5b87b9d38176bd98f23b58a8fb730e5124618d68571a011abbd38ad4a842/jupyterlab_server-1.0.6-py3-none-any.whl
Collecting notebook>=4.3.1
  Using cached https://files.pythonhosted.org/packages/f5/69/d2ffaf7efc20ce47469187e3a41e6e03e17b45de5a6559f4e7ab3eace5e1/notebook-6.0.2-py3-none-any.whl
Collecting MarkupSafe>=0.23
  Using cached https://files.pythonhosted.org/packages/5b/d4/1deb3c5dc3714fb160c7e2116fc6dff36a063d9156a9328cce54ef35cc52/MarkupSafe-1.1.1-cp37-cp37m-win32.whl
Collecting json5
  Using cached https://files.pythonhosted.org/packages/30/44/062543d4a6718f99d82e5ecf9140dbdee8a03122f2c34fbd0b0609891707/json5-0.8.5-py2.py3-none-any.whl
Collecting jsonschema>=3.0.1
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting Send2Trash
  Using cached https://files.pythonhosted.org/packages/49/46/c3dc27481d1cc57b9385aff41c474ceb7714f7935b1247194adae45db714/Send2Trash-1.5.0-py3-none-any.whl
Collecting traitlets>=4.2.1
  Using cached https://files.pythonhosted.org/packages/ca/ab/872a23e29cec3cf2594af7e857f18b687ad21039c1f9b922fac5b9b142d5/traitlets-4.3.3-py2.py3-none-any.whl
Collecting pyzmq>=17
  Downloading https://files.pythonhosted.org/packages/d7/64/021177b37977d3d5e659a8a44058906f834ef997b8cc09884812aecfa897/pyzmq-18.1.1-cp37-cp37m-win32.whl (900kB)
     |███████                         | 194kB 2.5kB/s eta 0:04:48ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\administrator\scoop\apps\python37\current\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "c:\users\administrator\scoop\apps\python37\current\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "c:\users\administrator\scoop\apps\python37\current\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\administrator\scoop\apps\python37\current\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\administrator\scoop\apps\python37\current\lib\ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 316, in unpack_http_url
    progress_bar)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 223, in written_chunks
    for chunk in chunks:
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\ui.py", line 160, in iter
    for x in it:
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 212, in resp_read
    decode_content=False):
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\administrator\scoop\apps\python37\current\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\administrator\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by kobeyyn** [comment]
错误更多了。。。

**Comment by kobeyyn** [comment]
用pip3 install jupyterlab，好像成功了

**Comment by neolee** [comment]
在你的系统里 pip 和 pip3 没区别，成不成看网络给不给力，成了就好……
