### ISSUE TITLE
macOS 下安装好 jupyter 后无法执行 jupyter lab

### ISSUE THREAD

**Issue by Lipsum-Takumi** [neolee/pilot#82]
0. 系统环境
macOS 10.15 Beta (19A573a), homebrew，python，jupyter 安装过程中无报错，有VPN（Surge）在运行，已复制终端代理命令

1. 执行命令
`Takumis-MacBook-Pro:pilot-student takumi$ jupyter lab`

2. 出现结果
预期：如同教程中，打开一个浏览器窗口
实际：
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/Library/Python/2.7/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-lab` not found.
```

3. 备注
安装的时候没能用 `pip install jupyterlab`安装成功，使用的是`pip install --user jupyterlab`

盼复，非常感谢🙏

**Comment by neolee** [comment]
你需要执行 pip install jupyterlab，这个为啥没执行成功？
