### ISSUE TITLE
安装Jupyter lab时出错 显示出错代码

### ISSUE THREAD

**Issue by DoctorX2019** [neolee/pilot#826]
老师，请问一下 我在conEmu下执行操作pip install jupyterlab时出现错误 ，请问这是什么原因导致的呢？ 我将命令改为pip3 install jupyterlab 之后也出现了这种情况。
下面是错误代码： 
OR: Exception:
Traceback (most recent call last):
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "c:\users\emma\scoop\apps\python37\current\lib\http\client.py", line 457, in read
    n = self.readinto(b)
  File "c:\users\emma\scoop\apps\python37\current\lib\http\client.py", line 501, in readinto
    n = self.fp.readinto(b)
  File "c:\users\emma\scoop\apps\python37\current\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "c:\users\emma\scoop\apps\python37\current\lib\ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "c:\users\emma\scoop\apps\python37\current\lib\ssl.py", line 929, in read

    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\operations\prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 316, in unpack_http_url
    progress_bar)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 253, in _download_url
    hashes.check_against_chunks(downloaded_chunks)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\hashes.py", line 80, in check_against_chunks
    for chunk in chunks:
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 223, in written_chunks
    for chunk in chunks:
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\utils\ui.py", line 160, in iter
    for x in it:
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_internal\download.py", line 212, in resp_read
    decode_content=False):
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "c:\users\emma\scoop\apps\python37\current\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\emma\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")

**Comment by DoctorX2019** [comment]
老师，我后来又试了几次，可能是网速问题 ，网速好的时候就安装成功了  ，其他参数都没有变
