### ISSUE TITLE
安装和运行 Jupyter Lab 失败

### ISSUE THREAD

**Issue by stsfg** [neolee/pilot#998]
PS C:\Users\stsfg> python -m pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
    2% |█                               | 40kB 3.3kB/s eta 0:07:00Exception:
Traceback (most recent call last):
  File "C:\Users\stsfg\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 360, in _error_catcher
    yield
  File "C:\Users\stsfg\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in read
    data = self._fp.read(amt)
  File "C:\Users\stsfg\scoop\apps\python37\current\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read

安装的时候会提示一大波错误，有时候在下载到2%的时候 有时候在50%的时候

**Comment by stsfg** [comment]
python -m pip install --upgrade pip -i https://pypi.douban.com/simple通过该代码解决了

**Comment by neolee** [comment]
`pip install` 命令实质上是从 PyPI（The Python Package Index）站点下载软件包并安装，我猜你的网络环境访问 PyPI 官方站点不太好，所以前面一次安装失败。

后面一个实际上是使用了豆瓣的 PyPI 镜像站点。国内有不少 PyPI 镜像，清华和豆瓣的都不错。
